### ISSUE TITLE
userprofile-pr #3 failed

### ISSUE THREAD

**Issue by hattanopenhackdevops** [HattanOpenHack/openhack-devops-team#26]
Build 'userprofile-pr' is failing!

Last 50 lines of build output:

```
[...truncated 57 lines...]
 ---> 799f7ef8ee59
Step 4/7 : EXPOSE 8080
 ---> Running in fd33c294287d
Removing intermediate container fd33c294287d
 ---> 1821a7d7bdfe
Step 5/7 : RUN npm install
 ---> Running in 925cd7470f00
[91mnpm WARN mydriving-user-api@1.0.0 No license field.
[0m[91m
[0madded 476 packages from 342 contributors and audited 1021 packages in 12.342s
found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container 925cd7470f00
 ---> e330a7a1b6a2
Step 6/7 : RUN npm run test
 ---> Running in 0c303e2c1054

> mydriving-user-api@1.0.0 test /app
> tape 'tests/**/*.js' | tap-junit --output reports --name userprofile-report

Finished! userprofile-report.xml created at: reports
[91mError: Looks like some test suites failed
    at xmlErr (/app/node_modules/tap-junit/src/index.js:43:25)
    at /app/node_modules/graceful-fs/graceful-fs.js:99:16
    at /app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
[0m[91mnpm[0m[91m ERR! [0m[91mcode ELIFECYCLE
[0m[91mnpm [0m[91mERR! errno 1
[0m[91mnpm [0m[91mERR![0m[91m mydriving-user-api@1.0.0 test: `tape 'tests/**/*.js' | tap-junit --output reports --name userprofile-report`
[0m[91mnpm[0m[91m ERR! Exit status 1
[0m[91mnpm ERR![0m[91m 
npm ERR![0m[91m Failed at the mydriving-user-api@1.0.0 test script.
npm [0m[91mERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
[0m[91mnpm ERR![0m[91m A complete log of this run can be found in:
npm ERR![0m[91m     /root/.npm/_logs/2018-11-22T20_41_23_944Z-debug.log
[0mThe command '/bin/sh -c npm run test' returned a non-zero code: 1
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
Post Build Results
[Pipeline] script
[Pipeline] {
[Pipeline] properties
[Pipeline] }
[Pipeline] // script
[Pipeline] step

```

Changes since last successful build:
No changes

[View full output](http://jenkinsopenhackff78.eastus.cloudapp.azure.com/job/userprofile-pr/3/)

**Comment by hattanopenhackdevops** [comment]
Build was fixed!
